development:
  adapter: mysql2
  database: clavis
  username: root
  password: rc223svt
  host: localhost
  encoding: utf8
  socket: /tmp/mysql.sock
  encoding: utf8
  reconnect: false
  pool: 5

production:
  adapter: mysql2
  database: clavis
  username: root
  password: rc223svt
  host: localhost
  encoding: utf8
  socket: /tmp/mysql.sock
  encoding: utf8
  reconnect: false
  pool: 5